/******************************************************************************
*                                                                             *
*  easycap_ioctlmess.c                                                        *
*                                                                             *
******************************************************************************/
/*
 *  THIS FILE IS WRITTEN AUTOMATICALLY BY SCRIPT ./ioctlmess.sh
 *  DURING DRIVER INSTALLATION.  DO NOT EDIT WITHOUT GOOD REASON.
*/
/*---------------------------------------------------------------------------*/

#include "easycap.h"

struct mess { __u32 command; char  name[64]; };

int explain_ioctl( struct easycap *peasycap, __u32 wot )
{
int k;
static const struct mess mess[] =
{
#if defined(VIDIOC_QUERYCAP)
{VIDIOC_QUERYCAP,"VIDIOC_QUERYCAP"},
#endif
#if defined(VIDIOC_RESERVED)
{VIDIOC_RESERVED,"VIDIOC_RESERVED"},
#endif
#if defined(VIDIOC_ENUM_FMT)
{VIDIOC_ENUM_FMT,"VIDIOC_ENUM_FMT"},
#endif
#if defined(VIDIOC_G_FMT)
{VIDIOC_G_FMT,"VIDIOC_G_FMT"},
#endif
#if defined(VIDIOC_S_FMT)
{VIDIOC_S_FMT,"VIDIOC_S_FMT"},
#endif
#if defined(VIDIOC_REQBUFS)
{VIDIOC_REQBUFS,"VIDIOC_REQBUFS"},
#endif
#if defined(VIDIOC_QUERYBUF)
{VIDIOC_QUERYBUF,"VIDIOC_QUERYBUF"},
#endif
#if defined(VIDIOC_G_FBUF)
{VIDIOC_G_FBUF,"VIDIOC_G_FBUF"},
#endif
#if defined(VIDIOC_S_FBUF)
{VIDIOC_S_FBUF,"VIDIOC_S_FBUF"},
#endif
#if defined(VIDIOC_OVERLAY)
{VIDIOC_OVERLAY,"VIDIOC_OVERLAY"},
#endif
#if defined(VIDIOC_QBUF)
{VIDIOC_QBUF,"VIDIOC_QBUF"},
#endif
#if defined(VIDIOC_DQBUF)
{VIDIOC_DQBUF,"VIDIOC_DQBUF"},
#endif
#if defined(VIDIOC_STREAMON)
{VIDIOC_STREAMON,"VIDIOC_STREAMON"},
#endif
#if defined(VIDIOC_STREAMOFF)
{VIDIOC_STREAMOFF,"VIDIOC_STREAMOFF"},
#endif
#if defined(VIDIOC_G_PARM)
{VIDIOC_G_PARM,"VIDIOC_G_PARM"},
#endif
#if defined(VIDIOC_S_PARM)
{VIDIOC_S_PARM,"VIDIOC_S_PARM"},
#endif
#if defined(VIDIOC_G_STD)
{VIDIOC_G_STD,"VIDIOC_G_STD"},
#endif
#if defined(VIDIOC_S_STD)
{VIDIOC_S_STD,"VIDIOC_S_STD"},
#endif
#if defined(VIDIOC_ENUMSTD)
{VIDIOC_ENUMSTD,"VIDIOC_ENUMSTD"},
#endif
#if defined(VIDIOC_ENUMINPUT)
{VIDIOC_ENUMINPUT,"VIDIOC_ENUMINPUT"},
#endif
#if defined(VIDIOC_G_CTRL)
{VIDIOC_G_CTRL,"VIDIOC_G_CTRL"},
#endif
#if defined(VIDIOC_S_CTRL)
{VIDIOC_S_CTRL,"VIDIOC_S_CTRL"},
#endif
#if defined(VIDIOC_G_TUNER)
{VIDIOC_G_TUNER,"VIDIOC_G_TUNER"},
#endif
#if defined(VIDIOC_S_TUNER)
{VIDIOC_S_TUNER,"VIDIOC_S_TUNER"},
#endif
#if defined(VIDIOC_G_AUDIO)
{VIDIOC_G_AUDIO,"VIDIOC_G_AUDIO"},
#endif
#if defined(VIDIOC_S_AUDIO)
{VIDIOC_S_AUDIO,"VIDIOC_S_AUDIO"},
#endif
#if defined(VIDIOC_QUERYCTRL)
{VIDIOC_QUERYCTRL,"VIDIOC_QUERYCTRL"},
#endif
#if defined(VIDIOC_QUERYMENU)
{VIDIOC_QUERYMENU,"VIDIOC_QUERYMENU"},
#endif
#if defined(VIDIOC_G_INPUT)
{VIDIOC_G_INPUT,"VIDIOC_G_INPUT"},
#endif
#if defined(VIDIOC_S_INPUT)
{VIDIOC_S_INPUT,"VIDIOC_S_INPUT"},
#endif
#if defined(VIDIOC_G_OUTPUT)
{VIDIOC_G_OUTPUT,"VIDIOC_G_OUTPUT"},
#endif
#if defined(VIDIOC_S_OUTPUT)
{VIDIOC_S_OUTPUT,"VIDIOC_S_OUTPUT"},
#endif
#if defined(VIDIOC_ENUMOUTPUT)
{VIDIOC_ENUMOUTPUT,"VIDIOC_ENUMOUTPUT"},
#endif
#if defined(VIDIOC_G_AUDOUT)
{VIDIOC_G_AUDOUT,"VIDIOC_G_AUDOUT"},
#endif
#if defined(VIDIOC_S_AUDOUT)
{VIDIOC_S_AUDOUT,"VIDIOC_S_AUDOUT"},
#endif
#if defined(VIDIOC_G_MODULATOR)
{VIDIOC_G_MODULATOR,"VIDIOC_G_MODULATOR"},
#endif
#if defined(VIDIOC_S_MODULATOR)
{VIDIOC_S_MODULATOR,"VIDIOC_S_MODULATOR"},
#endif
#if defined(VIDIOC_G_FREQUENCY)
{VIDIOC_G_FREQUENCY,"VIDIOC_G_FREQUENCY"},
#endif
#if defined(VIDIOC_S_FREQUENCY)
{VIDIOC_S_FREQUENCY,"VIDIOC_S_FREQUENCY"},
#endif
#if defined(VIDIOC_CROPCAP)
{VIDIOC_CROPCAP,"VIDIOC_CROPCAP"},
#endif
#if defined(VIDIOC_G_CROP)
{VIDIOC_G_CROP,"VIDIOC_G_CROP"},
#endif
#if defined(VIDIOC_S_CROP)
{VIDIOC_S_CROP,"VIDIOC_S_CROP"},
#endif
#if defined(VIDIOC_G_JPEGCOMP)
{VIDIOC_G_JPEGCOMP,"VIDIOC_G_JPEGCOMP"},
#endif
#if defined(VIDIOC_S_JPEGCOMP)
{VIDIOC_S_JPEGCOMP,"VIDIOC_S_JPEGCOMP"},
#endif
#if defined(VIDIOC_QUERYSTD)
{VIDIOC_QUERYSTD,"VIDIOC_QUERYSTD"},
#endif
#if defined(VIDIOC_TRY_FMT)
{VIDIOC_TRY_FMT,"VIDIOC_TRY_FMT"},
#endif
#if defined(VIDIOC_ENUMAUDIO)
{VIDIOC_ENUMAUDIO,"VIDIOC_ENUMAUDIO"},
#endif
#if defined(VIDIOC_ENUMAUDOUT)
{VIDIOC_ENUMAUDOUT,"VIDIOC_ENUMAUDOUT"},
#endif
#if defined(VIDIOC_G_PRIORITY)
{VIDIOC_G_PRIORITY,"VIDIOC_G_PRIORITY"},
#endif
#if defined(VIDIOC_S_PRIORITY)
{VIDIOC_S_PRIORITY,"VIDIOC_S_PRIORITY"},
#endif
#if defined(VIDIOC_G_SLICED_VBI_CAP)
{VIDIOC_G_SLICED_VBI_CAP,"VIDIOC_G_SLICED_VBI_CAP"},
#endif
#if defined(VIDIOC_LOG_STATUS)
{VIDIOC_LOG_STATUS,"VIDIOC_LOG_STATUS"},
#endif
#if defined(VIDIOC_G_EXT_CTRLS)
{VIDIOC_G_EXT_CTRLS,"VIDIOC_G_EXT_CTRLS"},
#endif
#if defined(VIDIOC_S_EXT_CTRLS)
{VIDIOC_S_EXT_CTRLS,"VIDIOC_S_EXT_CTRLS"},
#endif
#if defined(VIDIOC_TRY_EXT_CTRLS)
{VIDIOC_TRY_EXT_CTRLS,"VIDIOC_TRY_EXT_CTRLS"},
#endif
#if defined(VIDIOC_ENUM_FRAMESIZES)
{VIDIOC_ENUM_FRAMESIZES,"VIDIOC_ENUM_FRAMESIZES"},
#endif
#if defined(VIDIOC_ENUM_FRAMEINTERVALS)
{VIDIOC_ENUM_FRAMEINTERVALS,"VIDIOC_ENUM_FRAMEINTERVALS"},
#endif
#if defined(VIDIOC_G_ENC_INDEX)
{VIDIOC_G_ENC_INDEX,"VIDIOC_G_ENC_INDEX"},
#endif
#if defined(VIDIOC_ENCODER_CMD)
{VIDIOC_ENCODER_CMD,"VIDIOC_ENCODER_CMD"},
#endif
#if defined(VIDIOC_TRY_ENCODER_CMD)
{VIDIOC_TRY_ENCODER_CMD,"VIDIOC_TRY_ENCODER_CMD"},
#endif
#if defined(VIDIOC_DBG_G_CHIP_IDENT)
{VIDIOC_DBG_G_CHIP_IDENT,"VIDIOC_DBG_G_CHIP_IDENT"},
#endif
#if defined(VIDIOC_S_HW_FREQ_SEEK)
{VIDIOC_S_HW_FREQ_SEEK,"VIDIOC_S_HW_FREQ_SEEK"},
#endif
#if defined(VIDIOC_OVERLAY_OLD)
{VIDIOC_OVERLAY_OLD,"VIDIOC_OVERLAY_OLD"},
#endif
#if defined(VIDIOC_S_PARM_OLD)
{VIDIOC_S_PARM_OLD,"VIDIOC_S_PARM_OLD"},
#endif
#if defined(VIDIOC_S_CTRL_OLD)
{VIDIOC_S_CTRL_OLD,"VIDIOC_S_CTRL_OLD"},
#endif
#if defined(VIDIOC_G_AUDIO_OLD)
{VIDIOC_G_AUDIO_OLD,"VIDIOC_G_AUDIO_OLD"},
#endif
#if defined(VIDIOC_G_AUDOUT_OLD)
{VIDIOC_G_AUDOUT_OLD,"VIDIOC_G_AUDOUT_OLD"},
#endif
#if defined(VIDIOC_CROPCAP_OLD)
{VIDIOC_CROPCAP_OLD,"VIDIOC_CROPCAP_OLD"},
#endif
{0xFFFFFFFF,""},
};
static const struct mess mess1[] =
{
#if defined(VIDIOCGMBUF)
{VIDIOCGMBUF,"VIDIOCGMBUF"},
#endif
#if defined(VIDIOCGCAP)
{VIDIOCGCAP,"VIDIOCGCAP"},
#endif
#if defined(VIDIOCGCHAN)
{VIDIOCGCHAN,"VIDIOCGCHAN"},
#endif
#if defined(VIDIOCSCHAN)
{VIDIOCSCHAN,"VIDIOCSCHAN"},
#endif
#if defined(VIDIOCGTUNER)
{VIDIOCGTUNER,"VIDIOCGTUNER"},
#endif
#if defined(VIDIOCSTUNER)
{VIDIOCSTUNER,"VIDIOCSTUNER"},
#endif
#if defined(VIDIOCGPICT)
{VIDIOCGPICT,"VIDIOCGPICT"},
#endif
#if defined(VIDIOCSPICT)
{VIDIOCSPICT,"VIDIOCSPICT"},
#endif
#if defined(VIDIOCCAPTURE)
{VIDIOCCAPTURE,"VIDIOCCAPTURE"},
#endif
#if defined(VIDIOCGWIN)
{VIDIOCGWIN,"VIDIOCGWIN"},
#endif
#if defined(VIDIOCSWIN)
{VIDIOCSWIN,"VIDIOCSWIN"},
#endif
#if defined(VIDIOCGFBUF)
{VIDIOCGFBUF,"VIDIOCGFBUF"},
#endif
#if defined(VIDIOCSFBUF)
{VIDIOCSFBUF,"VIDIOCSFBUF"},
#endif
#if defined(VIDIOCKEY)
{VIDIOCKEY,"VIDIOCKEY"},
#endif
#if defined(VIDIOCGFREQ)
{VIDIOCGFREQ,"VIDIOCGFREQ"},
#endif
#if defined(VIDIOCSFREQ)
{VIDIOCSFREQ,"VIDIOCSFREQ"},
#endif
#if defined(VIDIOCGAUDIO)
{VIDIOCGAUDIO,"VIDIOCGAUDIO"},
#endif
#if defined(VIDIOCSAUDIO)
{VIDIOCSAUDIO,"VIDIOCSAUDIO"},
#endif
#if defined(VIDIOCSYNC)
{VIDIOCSYNC,"VIDIOCSYNC"},
#endif
#if defined(VIDIOCMCAPTURE)
{VIDIOCMCAPTURE,"VIDIOCMCAPTURE"},
#endif
#if defined(VIDIOCGMBUF)
{VIDIOCGMBUF,"VIDIOCGMBUF"},
#endif
#if defined(VIDIOCGUNIT)
{VIDIOCGUNIT,"VIDIOCGUNIT"},
#endif
#if defined(VIDIOCGCAPTURE)
{VIDIOCGCAPTURE,"VIDIOCGCAPTURE"},
#endif
#if defined(VIDIOCSCAPTURE)
{VIDIOCSCAPTURE,"VIDIOCSCAPTURE"},
#endif
#if defined(VIDIOCSPLAYMODE)
{VIDIOCSPLAYMODE,"VIDIOCSPLAYMODE"},
#endif
#if defined(VIDIOCSWRITEMODE)
{VIDIOCSWRITEMODE,"VIDIOCSWRITEMODE"},
#endif
#if defined(VIDIOCGPLAYINFO)
{VIDIOCGPLAYINFO,"VIDIOCGPLAYINFO"},
#endif
#if defined(VIDIOCSMICROCODE)
{VIDIOCSMICROCODE,"VIDIOCSMICROCODE"},
#endif
{0xFFFFFFFF,""},
};

k = 0;
while ( mess[k].name[0] )
  {
  if ( wot == mess[k].command )
    {
    SAM("ioctl 0x%08X is %s\n", mess[k].command, &mess[k].name[0]);
    return(0);
    }
  k++;
  }
SAM("ioctl 0x%08X is not in videodev2.h\n", wot );

k = 0;
while ( mess1[k].name[0] )
  {
  if ( wot == mess1[k].command )
    {
    SAM("ioctl 0x%08X is %s (V4L1)\n", mess1[k].command, &mess1[k].name[0]);
    return(0);
    }
  k++;
  }
SAM("ioctl 0x%08X is not in videodev.h\n", wot );
return(-ENOENT);
}
/*****************************************************************************/
int explain_cid( struct easycap *peasycap, __u32 wot )
{
int k;
static const struct mess mess[] =
{
#if defined(V4L2_CID_BASE)
{V4L2_CID_BASE,"V4L2_CID_BASE"},
#endif
#if defined(V4L2_CID_USER_BASE)
{V4L2_CID_USER_BASE,"V4L2_CID_USER_BASE"},
#endif
#if defined(V4L2_CID_PRIVATE_BASE)
{V4L2_CID_PRIVATE_BASE,"V4L2_CID_PRIVATE_BASE"},
#endif
#if defined(V4L2_CID_USER_CLASS)
{V4L2_CID_USER_CLASS,"V4L2_CID_USER_CLASS"},
#endif
#if defined(V4L2_CID_BRIGHTNESS)
{V4L2_CID_BRIGHTNESS,"V4L2_CID_BRIGHTNESS"},
#endif
#if defined(V4L2_CID_CONTRAST)
{V4L2_CID_CONTRAST,"V4L2_CID_CONTRAST"},
#endif
#if defined(V4L2_CID_SATURATION)
{V4L2_CID_SATURATION,"V4L2_CID_SATURATION"},
#endif
#if defined(V4L2_CID_HUE)
{V4L2_CID_HUE,"V4L2_CID_HUE"},
#endif
#if defined(V4L2_CID_AUDIO_VOLUME)
{V4L2_CID_AUDIO_VOLUME,"V4L2_CID_AUDIO_VOLUME"},
#endif
#if defined(V4L2_CID_AUDIO_BALANCE)
{V4L2_CID_AUDIO_BALANCE,"V4L2_CID_AUDIO_BALANCE"},
#endif
#if defined(V4L2_CID_AUDIO_BASS)
{V4L2_CID_AUDIO_BASS,"V4L2_CID_AUDIO_BASS"},
#endif
#if defined(V4L2_CID_AUDIO_TREBLE)
{V4L2_CID_AUDIO_TREBLE,"V4L2_CID_AUDIO_TREBLE"},
#endif
#if defined(V4L2_CID_AUDIO_MUTE)
{V4L2_CID_AUDIO_MUTE,"V4L2_CID_AUDIO_MUTE"},
#endif
#if defined(V4L2_CID_AUDIO_LOUDNESS)
{V4L2_CID_AUDIO_LOUDNESS,"V4L2_CID_AUDIO_LOUDNESS"},
#endif
#if defined(V4L2_CID_BLACK_LEVEL)
{V4L2_CID_BLACK_LEVEL,"V4L2_CID_BLACK_LEVEL"},
#endif
#if defined(V4L2_CID_AUTO_WHITE_BALANCE)
{V4L2_CID_AUTO_WHITE_BALANCE,"V4L2_CID_AUTO_WHITE_BALANCE"},
#endif
#if defined(V4L2_CID_DO_WHITE_BALANCE)
{V4L2_CID_DO_WHITE_BALANCE,"V4L2_CID_DO_WHITE_BALANCE"},
#endif
#if defined(V4L2_CID_RED_BALANCE)
{V4L2_CID_RED_BALANCE,"V4L2_CID_RED_BALANCE"},
#endif
#if defined(V4L2_CID_BLUE_BALANCE)
{V4L2_CID_BLUE_BALANCE,"V4L2_CID_BLUE_BALANCE"},
#endif
#if defined(V4L2_CID_GAMMA)
{V4L2_CID_GAMMA,"V4L2_CID_GAMMA"},
#endif
#if defined(V4L2_CID_WHITENESS)
{V4L2_CID_WHITENESS,"V4L2_CID_WHITENESS"},
#endif
#if defined(V4L2_CID_EXPOSURE)
{V4L2_CID_EXPOSURE,"V4L2_CID_EXPOSURE"},
#endif
#if defined(V4L2_CID_AUTOGAIN)
{V4L2_CID_AUTOGAIN,"V4L2_CID_AUTOGAIN"},
#endif
#if defined(V4L2_CID_GAIN)
{V4L2_CID_GAIN,"V4L2_CID_GAIN"},
#endif
#if defined(V4L2_CID_HFLIP)
{V4L2_CID_HFLIP,"V4L2_CID_HFLIP"},
#endif
#if defined(V4L2_CID_VFLIP)
{V4L2_CID_VFLIP,"V4L2_CID_VFLIP"},
#endif
#if defined(V4L2_CID_HCENTER)
{V4L2_CID_HCENTER,"V4L2_CID_HCENTER"},
#endif
#if defined(V4L2_CID_VCENTER)
{V4L2_CID_VCENTER,"V4L2_CID_VCENTER"},
#endif
#if defined(V4L2_CID_POWER_LINE_FREQUENCY)
{V4L2_CID_POWER_LINE_FREQUENCY,"V4L2_CID_POWER_LINE_FREQUENCY"},
#endif
#if defined(V4L2_CID_HUE_AUTO)
{V4L2_CID_HUE_AUTO,"V4L2_CID_HUE_AUTO"},
#endif
#if defined(V4L2_CID_WHITE_BALANCE_TEMPERATURE)
{V4L2_CID_WHITE_BALANCE_TEMPERATURE,"V4L2_CID_WHITE_BALANCE_TEMPERATURE"},
#endif
#if defined(V4L2_CID_SHARPNESS)
{V4L2_CID_SHARPNESS,"V4L2_CID_SHARPNESS"},
#endif
#if defined(V4L2_CID_BACKLIGHT_COMPENSATION)
{V4L2_CID_BACKLIGHT_COMPENSATION,"V4L2_CID_BACKLIGHT_COMPENSATION"},
#endif
#if defined(V4L2_CID_CHROMA_AGC)
{V4L2_CID_CHROMA_AGC,"V4L2_CID_CHROMA_AGC"},
#endif
#if defined(V4L2_CID_COLOR_KILLER)
{V4L2_CID_COLOR_KILLER,"V4L2_CID_COLOR_KILLER"},
#endif
#if defined(V4L2_CID_COLORFX)
{V4L2_CID_COLORFX,"V4L2_CID_COLORFX"},
#endif
#if defined(V4L2_CID_AUTOBRIGHTNESS)
{V4L2_CID_AUTOBRIGHTNESS,"V4L2_CID_AUTOBRIGHTNESS"},
#endif
#if defined(V4L2_CID_BAND_STOP_FILTER)
{V4L2_CID_BAND_STOP_FILTER,"V4L2_CID_BAND_STOP_FILTER"},
#endif
#if defined(V4L2_CID_LASTP1)
{V4L2_CID_LASTP1,"V4L2_CID_LASTP1"},
#endif
#if defined(V4L2_CID_MPEG_BASE)
{V4L2_CID_MPEG_BASE,"V4L2_CID_MPEG_BASE"},
#endif
#if defined(V4L2_CID_MPEG_CLASS)
{V4L2_CID_MPEG_CLASS,"V4L2_CID_MPEG_CLASS"},
#endif
#if defined(V4L2_CID_MPEG_STREAM_TYPE)
{V4L2_CID_MPEG_STREAM_TYPE,"V4L2_CID_MPEG_STREAM_TYPE"},
#endif
#if defined(V4L2_CID_MPEG_STREAM_PID_PMT)
{V4L2_CID_MPEG_STREAM_PID_PMT,"V4L2_CID_MPEG_STREAM_PID_PMT"},
#endif
#if defined(V4L2_CID_MPEG_STREAM_PID_AUDIO)
{V4L2_CID_MPEG_STREAM_PID_AUDIO,"V4L2_CID_MPEG_STREAM_PID_AUDIO"},
#endif
#if defined(V4L2_CID_MPEG_STREAM_PID_VIDEO)
{V4L2_CID_MPEG_STREAM_PID_VIDEO,"V4L2_CID_MPEG_STREAM_PID_VIDEO"},
#endif
#if defined(V4L2_CID_MPEG_STREAM_PID_PCR)
{V4L2_CID_MPEG_STREAM_PID_PCR,"V4L2_CID_MPEG_STREAM_PID_PCR"},
#endif
#if defined(V4L2_CID_MPEG_STREAM_PES_ID_AUDIO)
{V4L2_CID_MPEG_STREAM_PES_ID_AUDIO,"V4L2_CID_MPEG_STREAM_PES_ID_AUDIO"},
#endif
#if defined(V4L2_CID_MPEG_STREAM_PES_ID_VIDEO)
{V4L2_CID_MPEG_STREAM_PES_ID_VIDEO,"V4L2_CID_MPEG_STREAM_PES_ID_VIDEO"},
#endif
#if defined(V4L2_CID_MPEG_STREAM_VBI_FMT)
{V4L2_CID_MPEG_STREAM_VBI_FMT,"V4L2_CID_MPEG_STREAM_VBI_FMT"},
#endif
#if defined(V4L2_CID_MPEG_AUDIO_SAMPLING_FREQ)
{V4L2_CID_MPEG_AUDIO_SAMPLING_FREQ,"V4L2_CID_MPEG_AUDIO_SAMPLING_FREQ"},
#endif
#if defined(V4L2_CID_MPEG_AUDIO_ENCODING)
{V4L2_CID_MPEG_AUDIO_ENCODING,"V4L2_CID_MPEG_AUDIO_ENCODING"},
#endif
#if defined(V4L2_CID_MPEG_AUDIO_L1_BITRATE)
{V4L2_CID_MPEG_AUDIO_L1_BITRATE,"V4L2_CID_MPEG_AUDIO_L1_BITRATE"},
#endif
#if defined(V4L2_CID_MPEG_AUDIO_L2_BITRATE)
{V4L2_CID_MPEG_AUDIO_L2_BITRATE,"V4L2_CID_MPEG_AUDIO_L2_BITRATE"},
#endif
#if defined(V4L2_CID_MPEG_AUDIO_L3_BITRATE)
{V4L2_CID_MPEG_AUDIO_L3_BITRATE,"V4L2_CID_MPEG_AUDIO_L3_BITRATE"},
#endif
#if defined(V4L2_CID_MPEG_AUDIO_MODE)
{V4L2_CID_MPEG_AUDIO_MODE,"V4L2_CID_MPEG_AUDIO_MODE"},
#endif
#if defined(V4L2_CID_MPEG_AUDIO_MODE_EXTENSION)
{V4L2_CID_MPEG_AUDIO_MODE_EXTENSION,"V4L2_CID_MPEG_AUDIO_MODE_EXTENSION"},
#endif
#if defined(V4L2_CID_MPEG_AUDIO_EMPHASIS)
{V4L2_CID_MPEG_AUDIO_EMPHASIS,"V4L2_CID_MPEG_AUDIO_EMPHASIS"},
#endif
#if defined(V4L2_CID_MPEG_AUDIO_CRC)
{V4L2_CID_MPEG_AUDIO_CRC,"V4L2_CID_MPEG_AUDIO_CRC"},
#endif
#if defined(V4L2_CID_MPEG_AUDIO_MUTE)
{V4L2_CID_MPEG_AUDIO_MUTE,"V4L2_CID_MPEG_AUDIO_MUTE"},
#endif
#if defined(V4L2_CID_MPEG_AUDIO_AAC_BITRATE)
{V4L2_CID_MPEG_AUDIO_AAC_BITRATE,"V4L2_CID_MPEG_AUDIO_AAC_BITRATE"},
#endif
#if defined(V4L2_CID_MPEG_AUDIO_AC3_BITRATE)
{V4L2_CID_MPEG_AUDIO_AC3_BITRATE,"V4L2_CID_MPEG_AUDIO_AC3_BITRATE"},
#endif
#if defined(V4L2_CID_MPEG_VIDEO_ENCODING)
{V4L2_CID_MPEG_VIDEO_ENCODING,"V4L2_CID_MPEG_VIDEO_ENCODING"},
#endif
#if defined(V4L2_CID_MPEG_VIDEO_ASPECT)
{V4L2_CID_MPEG_VIDEO_ASPECT,"V4L2_CID_MPEG_VIDEO_ASPECT"},
#endif
#if defined(V4L2_CID_MPEG_VIDEO_B_FRAMES)
{V4L2_CID_MPEG_VIDEO_B_FRAMES,"V4L2_CID_MPEG_VIDEO_B_FRAMES"},
#endif
#if defined(V4L2_CID_MPEG_VIDEO_GOP_SIZE)
{V4L2_CID_MPEG_VIDEO_GOP_SIZE,"V4L2_CID_MPEG_VIDEO_GOP_SIZE"},
#endif
#if defined(V4L2_CID_MPEG_VIDEO_GOP_CLOSURE)
{V4L2_CID_MPEG_VIDEO_GOP_CLOSURE,"V4L2_CID_MPEG_VIDEO_GOP_CLOSURE"},
#endif
#if defined(V4L2_CID_MPEG_VIDEO_PULLDOWN)
{V4L2_CID_MPEG_VIDEO_PULLDOWN,"V4L2_CID_MPEG_VIDEO_PULLDOWN"},
#endif
#if defined(V4L2_CID_MPEG_VIDEO_BITRATE_MODE)
{V4L2_CID_MPEG_VIDEO_BITRATE_MODE,"V4L2_CID_MPEG_VIDEO_BITRATE_MODE"},
#endif
#if defined(V4L2_CID_MPEG_VIDEO_BITRATE)
{V4L2_CID_MPEG_VIDEO_BITRATE,"V4L2_CID_MPEG_VIDEO_BITRATE"},
#endif
#if defined(V4L2_CID_MPEG_VIDEO_BITRATE_PEAK)
{V4L2_CID_MPEG_VIDEO_BITRATE_PEAK,"V4L2_CID_MPEG_VIDEO_BITRATE_PEAK"},
#endif
#if defined(V4L2_CID_MPEG_VIDEO_TEMPORAL_DECIMATION)
{V4L2_CID_MPEG_VIDEO_TEMPORAL_DECIMATION,"V4L2_CID_MPEG_VIDEO_TEMPORAL_DECIMATION"},
#endif
#if defined(V4L2_CID_MPEG_VIDEO_MUTE)
{V4L2_CID_MPEG_VIDEO_MUTE,"V4L2_CID_MPEG_VIDEO_MUTE"},
#endif
#if defined(V4L2_CID_MPEG_VIDEO_MUTE_YUV)
{V4L2_CID_MPEG_VIDEO_MUTE_YUV,"V4L2_CID_MPEG_VIDEO_MUTE_YUV"},
#endif
#if defined(V4L2_CID_MPEG_CX2341X_BASE)
{V4L2_CID_MPEG_CX2341X_BASE,"V4L2_CID_MPEG_CX2341X_BASE"},
#endif
#if defined(V4L2_CID_MPEG_CX2341X_VIDEO_SPATIAL_FILTER_MODE)
{V4L2_CID_MPEG_CX2341X_VIDEO_SPATIAL_FILTER_MODE,"V4L2_CID_MPEG_CX2341X_VIDEO_SPATIAL_FILTER_MODE"},
#endif
#if defined(V4L2_CID_MPEG_CX2341X_VIDEO_SPATIAL_FILTER)
{V4L2_CID_MPEG_CX2341X_VIDEO_SPATIAL_FILTER,"V4L2_CID_MPEG_CX2341X_VIDEO_SPATIAL_FILTER"},
#endif
#if defined(V4L2_CID_MPEG_CX2341X_VIDEO_LUMA_SPATIAL_FILTER_TYPE)
{V4L2_CID_MPEG_CX2341X_VIDEO_LUMA_SPATIAL_FILTER_TYPE,"V4L2_CID_MPEG_CX2341X_VIDEO_LUMA_SPATIAL_FILTER_TYPE"},
#endif
#if defined(V4L2_CID_MPEG_CX2341X_VIDEO_CHROMA_SPATIAL_FILTER_TYPE)
{V4L2_CID_MPEG_CX2341X_VIDEO_CHROMA_SPATIAL_FILTER_TYPE,"V4L2_CID_MPEG_CX2341X_VIDEO_CHROMA_SPATIAL_FILTER_TYPE"},
#endif
#if defined(V4L2_CID_MPEG_CX2341X_VIDEO_TEMPORAL_FILTER_MODE)
{V4L2_CID_MPEG_CX2341X_VIDEO_TEMPORAL_FILTER_MODE,"V4L2_CID_MPEG_CX2341X_VIDEO_TEMPORAL_FILTER_MODE"},
#endif
#if defined(V4L2_CID_MPEG_CX2341X_VIDEO_TEMPORAL_FILTER)
{V4L2_CID_MPEG_CX2341X_VIDEO_TEMPORAL_FILTER,"V4L2_CID_MPEG_CX2341X_VIDEO_TEMPORAL_FILTER"},
#endif
#if defined(V4L2_CID_MPEG_CX2341X_VIDEO_MEDIAN_FILTER_TYPE)
{V4L2_CID_MPEG_CX2341X_VIDEO_MEDIAN_FILTER_TYPE,"V4L2_CID_MPEG_CX2341X_VIDEO_MEDIAN_FILTER_TYPE"},
#endif
#if defined(V4L2_CID_MPEG_CX2341X_VIDEO_LUMA_MEDIAN_FILTER_BOTTOM)
{V4L2_CID_MPEG_CX2341X_VIDEO_LUMA_MEDIAN_FILTER_BOTTOM,"V4L2_CID_MPEG_CX2341X_VIDEO_LUMA_MEDIAN_FILTER_BOTTOM"},
#endif
#if defined(V4L2_CID_MPEG_CX2341X_VIDEO_LUMA_MEDIAN_FILTER_TOP)
{V4L2_CID_MPEG_CX2341X_VIDEO_LUMA_MEDIAN_FILTER_TOP,"V4L2_CID_MPEG_CX2341X_VIDEO_LUMA_MEDIAN_FILTER_TOP"},
#endif
#if defined(V4L2_CID_MPEG_CX2341X_VIDEO_CHROMA_MEDIAN_FILTER_BOTTOM)
{V4L2_CID_MPEG_CX2341X_VIDEO_CHROMA_MEDIAN_FILTER_BOTTOM,"V4L2_CID_MPEG_CX2341X_VIDEO_CHROMA_MEDIAN_FILTER_BOTTOM"},
#endif
#if defined(V4L2_CID_MPEG_CX2341X_VIDEO_CHROMA_MEDIAN_FILTER_TOP)
{V4L2_CID_MPEG_CX2341X_VIDEO_CHROMA_MEDIAN_FILTER_TOP,"V4L2_CID_MPEG_CX2341X_VIDEO_CHROMA_MEDIAN_FILTER_TOP"},
#endif
#if defined(V4L2_CID_MPEG_CX2341X_STREAM_INSERT_NAV_PACKETS)
{V4L2_CID_MPEG_CX2341X_STREAM_INSERT_NAV_PACKETS,"V4L2_CID_MPEG_CX2341X_STREAM_INSERT_NAV_PACKETS"},
#endif
#if defined(V4L2_CID_CAMERA_CLASS_BASE)
{V4L2_CID_CAMERA_CLASS_BASE,"V4L2_CID_CAMERA_CLASS_BASE"},
#endif
#if defined(V4L2_CID_CAMERA_CLASS)
{V4L2_CID_CAMERA_CLASS,"V4L2_CID_CAMERA_CLASS"},
#endif
#if defined(V4L2_CID_EXPOSURE_AUTO)
{V4L2_CID_EXPOSURE_AUTO,"V4L2_CID_EXPOSURE_AUTO"},
#endif
#if defined(V4L2_CID_EXPOSURE_ABSOLUTE)
{V4L2_CID_EXPOSURE_ABSOLUTE,"V4L2_CID_EXPOSURE_ABSOLUTE"},
#endif
#if defined(V4L2_CID_EXPOSURE_AUTO_PRIORITY)
{V4L2_CID_EXPOSURE_AUTO_PRIORITY,"V4L2_CID_EXPOSURE_AUTO_PRIORITY"},
#endif
#if defined(V4L2_CID_PAN_RELATIVE)
{V4L2_CID_PAN_RELATIVE,"V4L2_CID_PAN_RELATIVE"},
#endif
#if defined(V4L2_CID_TILT_RELATIVE)
{V4L2_CID_TILT_RELATIVE,"V4L2_CID_TILT_RELATIVE"},
#endif
#if defined(V4L2_CID_PAN_RESET)
{V4L2_CID_PAN_RESET,"V4L2_CID_PAN_RESET"},
#endif
#if defined(V4L2_CID_TILT_RESET)
{V4L2_CID_TILT_RESET,"V4L2_CID_TILT_RESET"},
#endif
#if defined(V4L2_CID_PAN_ABSOLUTE)
{V4L2_CID_PAN_ABSOLUTE,"V4L2_CID_PAN_ABSOLUTE"},
#endif
#if defined(V4L2_CID_TILT_ABSOLUTE)
{V4L2_CID_TILT_ABSOLUTE,"V4L2_CID_TILT_ABSOLUTE"},
#endif
#if defined(V4L2_CID_FOCUS_ABSOLUTE)
{V4L2_CID_FOCUS_ABSOLUTE,"V4L2_CID_FOCUS_ABSOLUTE"},
#endif
#if defined(V4L2_CID_FOCUS_RELATIVE)
{V4L2_CID_FOCUS_RELATIVE,"V4L2_CID_FOCUS_RELATIVE"},
#endif
#if defined(V4L2_CID_FOCUS_AUTO)
{V4L2_CID_FOCUS_AUTO,"V4L2_CID_FOCUS_AUTO"},
#endif
#if defined(V4L2_CID_ZOOM_ABSOLUTE)
{V4L2_CID_ZOOM_ABSOLUTE,"V4L2_CID_ZOOM_ABSOLUTE"},
#endif
#if defined(V4L2_CID_ZOOM_RELATIVE)
{V4L2_CID_ZOOM_RELATIVE,"V4L2_CID_ZOOM_RELATIVE"},
#endif
#if defined(V4L2_CID_ZOOM_CONTINUOUS)
{V4L2_CID_ZOOM_CONTINUOUS,"V4L2_CID_ZOOM_CONTINUOUS"},
#endif
#if defined(V4L2_CID_PRIVACY)
{V4L2_CID_PRIVACY,"V4L2_CID_PRIVACY"},
#endif
#if defined(V4L2_CID_FM_TX_CLASS_BASE)
{V4L2_CID_FM_TX_CLASS_BASE,"V4L2_CID_FM_TX_CLASS_BASE"},
#endif
#if defined(V4L2_CID_FM_TX_CLASS)
{V4L2_CID_FM_TX_CLASS,"V4L2_CID_FM_TX_CLASS"},
#endif
#if defined(V4L2_CID_RDS_TX_DEVIATION)
{V4L2_CID_RDS_TX_DEVIATION,"V4L2_CID_RDS_TX_DEVIATION"},
#endif
#if defined(V4L2_CID_RDS_TX_PI)
{V4L2_CID_RDS_TX_PI,"V4L2_CID_RDS_TX_PI"},
#endif
#if defined(V4L2_CID_RDS_TX_PTY)
{V4L2_CID_RDS_TX_PTY,"V4L2_CID_RDS_TX_PTY"},
#endif
#if defined(V4L2_CID_RDS_TX_PS_NAME)
{V4L2_CID_RDS_TX_PS_NAME,"V4L2_CID_RDS_TX_PS_NAME"},
#endif
#if defined(V4L2_CID_RDS_TX_RADIO_TEXT)
{V4L2_CID_RDS_TX_RADIO_TEXT,"V4L2_CID_RDS_TX_RADIO_TEXT"},
#endif
#if defined(V4L2_CID_AUDIO_LIMITER_ENABLED)
{V4L2_CID_AUDIO_LIMITER_ENABLED,"V4L2_CID_AUDIO_LIMITER_ENABLED"},
#endif
#if defined(V4L2_CID_AUDIO_LIMITER_RELEASE_TIME)
{V4L2_CID_AUDIO_LIMITER_RELEASE_TIME,"V4L2_CID_AUDIO_LIMITER_RELEASE_TIME"},
#endif
#if defined(V4L2_CID_AUDIO_LIMITER_DEVIATION)
{V4L2_CID_AUDIO_LIMITER_DEVIATION,"V4L2_CID_AUDIO_LIMITER_DEVIATION"},
#endif
#if defined(V4L2_CID_AUDIO_COMPRESSION_ENABLED)
{V4L2_CID_AUDIO_COMPRESSION_ENABLED,"V4L2_CID_AUDIO_COMPRESSION_ENABLED"},
#endif
#if defined(V4L2_CID_AUDIO_COMPRESSION_GAIN)
{V4L2_CID_AUDIO_COMPRESSION_GAIN,"V4L2_CID_AUDIO_COMPRESSION_GAIN"},
#endif
#if defined(V4L2_CID_AUDIO_COMPRESSION_THRESHOLD)
{V4L2_CID_AUDIO_COMPRESSION_THRESHOLD,"V4L2_CID_AUDIO_COMPRESSION_THRESHOLD"},
#endif
#if defined(V4L2_CID_AUDIO_COMPRESSION_ATTACK_TIME)
{V4L2_CID_AUDIO_COMPRESSION_ATTACK_TIME,"V4L2_CID_AUDIO_COMPRESSION_ATTACK_TIME"},
#endif
#if defined(V4L2_CID_AUDIO_COMPRESSION_RELEASE_TIME)
{V4L2_CID_AUDIO_COMPRESSION_RELEASE_TIME,"V4L2_CID_AUDIO_COMPRESSION_RELEASE_TIME"},
#endif
#if defined(V4L2_CID_PILOT_TONE_ENABLED)
{V4L2_CID_PILOT_TONE_ENABLED,"V4L2_CID_PILOT_TONE_ENABLED"},
#endif
#if defined(V4L2_CID_PILOT_TONE_DEVIATION)
{V4L2_CID_PILOT_TONE_DEVIATION,"V4L2_CID_PILOT_TONE_DEVIATION"},
#endif
#if defined(V4L2_CID_PILOT_TONE_FREQUENCY)
{V4L2_CID_PILOT_TONE_FREQUENCY,"V4L2_CID_PILOT_TONE_FREQUENCY"},
#endif
#if defined(V4L2_CID_TUNE_PREEMPHASIS)
{V4L2_CID_TUNE_PREEMPHASIS,"V4L2_CID_TUNE_PREEMPHASIS"},
#endif
#if defined(V4L2_CID_TUNE_POWER_LEVEL)
{V4L2_CID_TUNE_POWER_LEVEL,"V4L2_CID_TUNE_POWER_LEVEL"},
#endif
#if defined(V4L2_CID_TUNE_ANTENNA_CAPACITOR)
{V4L2_CID_TUNE_ANTENNA_CAPACITOR,"V4L2_CID_TUNE_ANTENNA_CAPACITOR"},
#endif
{0xFFFFFFFF,""},
};

k = 0;
while ( mess[k].name[0] )
  {
  if ( wot == mess[k].command )
    {
    SAM("ioctl 0x%08X is %s\n", mess[k].command, &mess[k].name[0]);
    return(0);
    }
  k++;
  }
SAM("cid 0x%08X is not in videodev2.h\n", wot );
return(-ENOENT);
}
/*****************************************************************************/
